In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('delta T.csv')

In [16]:
df

     hr     hc  totalT     RT     CT
0  4.87  12.01   24.78  24.77  24.89
1  5.20  12.77   29.75  29.73  30.46
2  5.48  13.35   34.05  34.71  34.75
3  5.73  13.71   39.72  39.71  39.85
4  5.96  13.95   44.70  44.73  44.36
5  6.19  14.15   49.67  49.66  49.99
6  6.40  14.43   54.90  54.70  54.69
7  6.61  14.45   59.83  59.71  59.68
8  6.82  14.67   65.16  64.70  64.00

In [17]:
loghc = y1 log x + y2 log hr + y3 log delta T

SyntaxError: invalid syntax (<ipython-input-17-0c2d7c3f5e51>, line 1)

In [27]:
y = np.log(df)['hc']

X = np.log(df).drop(['hc', 'RT', 'CT'], 1)

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
lm = LinearRegression()

In [30]:
lm.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
lm.score(X, y)

0.9543216735799688

In [32]:
lm.intercept_

1.3813549155472828

In [33]:
X

         hr    totalT
0  1.583094  3.210037
1  1.648659  3.392829
2  1.701105  3.527830
3  1.745716  3.681855
4  1.785070  3.799974
5  1.822935  3.905401
6  1.856298  4.005513
7  1.888584  4.091507
8  1.919859  4.176846

In [34]:
lm.coef_

array([ 1.04195486, -0.16273972])

$$log(h_c) = b_0 + b_1 log(h_r) + b_2 log (Total\ \Delta T)$$
$$b_0=1.3813549155472828$$
$$b_1=1.04195486$$
$$b_2=-0.16273972$$

In [ ]:
log hc = b0 + b1 log hr + b2 log TT

In [ ]:
hc = e**(b0 + b1 log(hr) + b2 log(TT))

e**b0 * e**(b1 log (hr)) * e**(b2 log(TT))

In [ ]:
hc = e**b0 * hr * e**b1 * TT * e ** b2

In [8]:
df = pd.read_csv('values.csv')

In [9]:
df.columns = df.loc[0]
df = df.drop(0)

$$\frac{h_r}{h_c} = x(T_c - T_a) ^{y}$$

In [10]:
df

,No,Folder\nNo,Condition,Iterations,Mesh,Radiator Surface\nTemperature\nK,Walls\nTemperature\nK,Radiator\nDimensions\ncm,Fresh Air \nVelocity\nm/s,Fresh Air\nTemperature\nK,...,ht\nW/m2 K,Nu,Area-weighted average\nWall\nyplus,Max\nWall\nyplus,AUST,Ta,Ts,Radiation\nΔT,Convection \nΔT,Total \nΔT
1,1-1,6,Radiator,"5,000","138,246",313,293,110 x 55 x 10,2,285,...,16.93,699.77,NaN,NaN,288.23,288.11,313.00,24.77,24.89,24.78
2,1-2,8,Radiator,"5,000","138,246",318,293,110 x 55 x 10,2,285,...,18.27,754.91,5.30,18.57,288.27,287.54,318.00,29.73,30.46,29.75
3,1-3,9,Radiator,"5,000","138,246",323,293,110 x 55 x 10,2,285,...,19.21,793.60,5.87,18.00,288.29,288.25,323.00,34.71,34.75,34.05
4,1-4,10,Radiator,"5,000","138,246",328,293,110 x 55 x 10,2,285,...,19.48,805.10,5.62,18.74,288.29,288.15,328.00,39.71,39.85,39.72
5,1-5,11,Radiator,"5,000","138,246",333,293,110 x 55 x 10,2,285,...,19.81,818.56,5.89,19.29,288.27,288.64,333.00,44.73,44.36,44.70
6,1-6,12,Radiator,"5,000","138,246",338,293,110 x 55 x 10,2,285,...,20.43,844.03,6.00,21.57,288.34,288.01,338.00,49.66,49.99,49.67
7,1-7,13,Radiator,"5,000","138,246",343,293,110 x 55 x 10,2,285,...,20.75,857.38,5.99,19.10,288.30,288.31,343.00,54.70,54.69,54.90
8,1-8,14,Radiator,"5,000","138,246",348,293,110 x 55 x 10,2,285,...,21.01,868.07,6.23,19.17,288.29,288.32,348.00,59.71,59.68,59.83
9,1-9,15,Radiator,"5,000","138,246",353,293,110 x 55 x 10,2,285,...,21.18,875.28,6.33,20.58,288.30,289.00,353.00,64.70,64.00,65.16
10,2-1,16,Radiator,"5,000","138,246",313,293,110 x 55 x 10,1.5,285,...,16.40,677.84,4.40,14.77,288.22,288.53,313.00,24.78,24.47,24.78
11,2-2,17,Radiator,"5,000","138,246",318,293,110 x 55 x 10,1.5,285,...,17.64,728.84,4.88,15.13,288.26,288.60,318.00,29.74,29.40,29.71
12,2-3,18,Radiator,"5,000","138,246",323,293,110 x 55 x 10,1.5,285,...,18.86,779.28,4.83,16.99,288.17,287.64,323.00,34.83,35.36,34.74
13,2-4,19,Radiator,"5,000","138,246",328,293,110 x 55 x 10,1.5,285,...,18.94,782.57,5.31,17.06,288.28,288.61,328.00,39.72,39.39,39.72
14,2-5,20,Radiator,"5,000","138,246",333,293,110 x 55 x 10,1.5,285,...,19.80,818.11,5.53,17.70,288.27,288.27,333.00,44.73,44.73,43.92
15,2-6,21,Radiator,"5,000","138,246",338,293,110 x 55 x 10,1.5,285,...,19.87,820.91,5.71,19.99,288.33,288.79,338.00,49.67,49.21,49.43
16,2-7,22,Radiator,"5,000","138,246",343,293,110 x 55 x 10,1.5,285,...,20.38,842.09,5.90,20.56,288.29,288.25,343.00,54.71,54.75,54.66
17,2-8,23,Radiator,"5,000","138,246",348,293,110 x 55 x 10,1.5,285,...,20.72,856.01,6.02,17.06,288.28,288.42,348.00,59.72,59.58,59.63
18,2-9,24,Radiator,"5,000","138,246",353,293,110 x 55 x 10,1.5,285,...,21.06,894.71,6.22,21.34,288.31,288.71,353.00,64.69,64.29,64.60
19,3-1,25,Radiator,"5,000","138,246",313,293,110 x 55 x 10,2.5,285,...,17.15,708.15,5.46,20.57,288.23,288.28,313.00,24.77,24.72,24.77
20,3-2,26,Radiator,"5,000","138,246",318,293,110 x 55 x 10,2.5,285,...,18.16,750.43,6.18,22.85,288.27,288.30,318.00,29.73,29.70,29.76
21,3-3,27,Radiator,"5,000","138,246",323,293,110 x 55 x 10,2.5,285,...,19.17,792.04,5.92,20.55,288.29,288.24,323.00,34.71,34.76,34.73
22,3-4,28,Radiator,"5,000","138,246",328,293,110 x 55 x 10,2.5,285,...,19.94,823.80,5.99,20.71,288.29,288.18,328.00,39.71,39.82,39.71
23,3-5,29,Radiator,"5,000","138,246",333,293,110 x 55 x 10,2.5,285,...,20.46,845.34,6.22,16.97,288.28,288.26,333.00,44.72,44.74,44.06
24,3-6,30,Radiator,"5,000","138,246",338,293,110 x 55 x 10,2.5,285,...,20.61,851.66,6.21,19.18,288.34,288.32,338.00,49.66,49.68,49.67
25,3-7,31,Radiator,"5,000","138,246",343,293,110 x 55 x 10,2.5,285,...,20.81,859.86,6.53,23.37,288.30,288.32,343.00,54.70,54.68,55.71
26,3-8,32,Radiator,"5,000","138,246",348,293,110 x 55 x 10,2.5,285,...,21.55,890.69,6.48,20.37,288.30,288.31,348.00,59.70,59.69,59.64
27,3-9,33,Radiator,"5,000","138,246",353,293,110 x 55 x 10,2.5,285,...,22.05,911.16,6.30,21.43,288.32,288.43,353.00,64.68,64.57,64.60

In [ ]:
X

U @ S @ V

In [ ]:
x, y = make_blobs(900, 4, 5)
cov = x.T @ x
u, s, v = np.linalg.svd(cov)
print('U @ S @ V = cov')
print((cov - (u @ np.diag(s) @ v)) < 1e-9)
print('ilk satirin ikinci satir uzerine izdusumu:')
print((u[0:1] @ u[1:2].T).round(2))  # herhangi iki satir/sutunun matris carpimi 0
print('Tum sutunlarin diger sutunlar uzerine izdusumu (yalnizca kendi uzerine izdusumleri birim uzunluk):')
print((u @ u.T).round(2))   # yukaridaki olayin tum satir/sutunlar icin gosterimi
print('Sutun uzunluklari:')
print((u**2).sum(axis=1))   # sutunlar birim uzunluga esit
print('Satir uzunluklari:')
print((u**2).sum(axis=0))   # satirlar birim uzunluga esit
print('Korunan varyans orani:')
print(s/s.sum())